// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugevskvvitewkbyfjoai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnZXZza3Z2aXRld2tieWZqb2FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDY5NzksImV4cCI6MjA2MzgyMjk3OX0.UZKzvpHzIIkdqzcNu3VTCxD-p_DPsRTsBmL9Tl7C8QY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);